services:
  - type: web
    name: intellirag-backend
    env: docker
    region: ohio
    plan: starter
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: models/gemini-flash-latest
      - key: COHERE_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
